version: '3.8'
services:
  
  api:
    build: 
      context: .  
      dockerfile: dockerfile
    ports:
      - "8080:8888"
    environment:
      - MONGO_URI =  mongodb+srv://Tanmay-Kanase:Tanmay%400707@mern-estate.q2kedho.mongodb.net/mern-estate?retryWrites=true&w=majority&appName=mern-estate
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - api


